version: '3'
services:
  web:
    image: web
    build: ./docker/web
    volumes:
      - ./www:/var/www/html/pdf/
    ports:
      - 8085:80
volumes:
  web-build-composer:
  web-build-node:
  npm-cache:
